name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run Backend Tests
      working-directory: ./backend
      run: npm test

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build

    - name: Deploy to Local Server
      env:
        HOST: ${{ secrets.SERVER_HOST }}
        USERNAME: ${{ secrets.SERVER_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
        scp -o StrictHostKeyChecking=no -i key.pem -r ./backend ./frontend $USERNAME@$HOST:/path/to/deploy/
        ssh -i key.pem $USERNAME@$HOST 'bash -s' < ./scripts/deploy.sh
        rm key.pem
